### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by someburner** [daviddpd/dpdChatFabric#5]
Hi there! I'm interested in implementing something similar to this into my ESP8266-based project. 

I noticed the readme says:

> libsodium proved to be difficult to port to ESP8266/xtensa-lx106

I'm not very familiar with libsodium, but I was wondering what some of the issues you encountered were? I don't need the full library, but I am using SDK 1.5.4.1 with the open source lwip and compiling with esp-open-sdk. I'm also using rBoot and SPIFFS so I don't think I can implement your code verbatim. I'd like to create a little more general-purpose library that can be used with esp-open-sdk without as many project-specific definitions.

I also noticed you said you encountered issues with SDK 1.4+. Not sure what you encountered our what you tried, but I know that the linker scripts changed a bit from 1.3-1.4 and they definitely increased their use of IRAM.

I'm thinking that it may be easier in the long run to cross-compile libsodium as part of the esp-open-sdk toolchain installation, but I'm a total noob when it comes to that stuff. I have some time on my hands so I'm willing to give it a shot, but I wanted to see what you tried/encountered first to perhaps save myself some time in the process.

Thanks in advance!

Ps- I watched your January 2016 youtube video demo. First off - cool stuff! I was wondering if for connecting the device to the home network if you had considered the SmartConfig library provided by Espressif at all? Obviously a bit less secure but allows you to connect the ESP without connecting a phone to the ESP.

**Comment by daviddpd** [comment]
libsodium - was likely a year or year and half ago when I tried - I don't specifically remember.    It was likely some compiler or external function call that was not possibly to easily translate into the xtensa-lx106 compiler.  I'll look around and see if I have the attempt I was doing.  I didn't spend a lot of time on it, and hit it really early on in the process.

There was also a university project overseas that was porting libsodium to smaller platforms, but never heard back from them either.

There are a few test files in dpdChatFabric/tools for crypto testing.  I probably have some test files somewhere that uses libsodium to encrypt, but the stand-alone functions to decrypt, etc, to verify that things work.

However, I've found the stand along reference implementations fast enough, and slightly easier to work with and read. I am missing the reference implementation for chacah20 (with 96 bits nonce).  So I'm currently using salas20-poly1305 with curve25519 keys.  The chacha20 with 96 bit NONCE (RFC 7539) is done plenty of places, I just don't have enough knowledge to get back into a a nice, small C99 implementation. 

I've been trying to get help with the 1.4+ problem, but doesn't seem to be wide spread.  Still trying to nail it down.   Issues is documented here:
- http://bbs.espressif.com/viewtopic.php?f=7&t=1616&p=9776#p9776

And having a bit of a back and forth with the Arduino developer here : 
- https://twitter.com/daviddpd/status/774680029959684096

As far as the SDK goes ... 1.3 is working pretty good for now.  I'd still love to up to 2.0.x, and use the included NTP instead of my stand alone. 

I am going to need IPv6 support at some point. I think the FreeRTOS has IPv6, the NON-OS SDK does not.  So at some point, I need to move.  I tried the RTOS briefly once, but gave up on it for some reason. 

I'm hoping to create a open, secure, cloud-less and hub-less platform.   Since the internals of smart config seemly are pretty closed ... and horribly insecure, I'd like to avoid it.   chatFabric does need a bunch of work in this area - like implementing a copy-from-phone config setting.   A smartConfig like system could easily added into chatFabric, which seemly would be more flexible and secure.    But chatFabric should be more of a protocol (think  instead of HTTP+JSON)  ... so a chatFabric device, could optionally use smartConfig. 

But auto-configuring a device, blindly, is a horrible idea.  There should be some sort of auth done, even if its some sort of pre-load of keys or mac addresses or something.  A much user-friendly and simpler configuration is much needed.   A light or outlet may not be a big deal ... but locks, garage doors, and cameras ... need to be secure.

**Comment by someburner** [comment]
Yeah I tried the xtensa-lx106  as host for libsodium and it doesn't seem to like the C compiler. Not sure how much effort would have to go into making that work, so I'll probably hold off for now. 

Strange about your issues with SDK 1.4.x, 1.5.x. The only thing I could think of off the top of my head is that they released a patch for versions >1.3 and you have to flash a couple sectors & add a block of code to user_main.c to get it to perform some RF calibration stuff. But I'm presuming that issue is not related to your ChatFabric code?

I'll probably try to get going with your standalone code before taking a deep dive into cross-compiling anything. I'll let you know how it goes. One thing, could you explain the `CP_ICACHE_FLASH_ATTR` attributes a bit? Is that just to allow you to build it from the same source on BSD?

Yeah IPv6 is RTOS-only AFAIK. But also given the limited resources of the ESP8266 I would probably just start out with the ESP32. Your project sounds interesting though. I suppose your interest in IPv6 is to make the device accessible to the phone even if you are away from home?

My project is a water monitoring system, so the ESP only acts as a gateway to a cloud service and communicates with another device on a water meter using RF modules that have HW encryption. In case you're interested, the module is RFM69. For us it's basically a requirement as WiFi range 100ft outside a house is not a given. So it's a one-time WiFi client setup that can only be activated by pushing a physical button. The risk would be another device in range using the same protocol to intercept the WiFi details during the one-time.. unlikely but it would probably be a good idea to add some encryption to that somehow which we plan to do. I think you can transmit whatever payload you want so we could probably preload some keys and encrypt the payload from the phone. FYI, the NodeMCU has an OS implementation of the SmartConfig protocol [here](https://github.com/nodemcu/nodemcu-firmware/tree/master/app/smart).

**Comment by daviddpd** [comment]
What's your need for libsodium/encryption right now ?  

I think I've reproduced the WiFi issue without the chatFabric code, but it is possible ... however, whatever it is ... it is something that changed  between 1.3 and 1.4.  I'm going to get another AP and see if it makes a difference too. blah blah ... lots of testing and debugging - that if its not in my own code - shouldn't be doing.

The ESP32 isn't quite available yet, and I've been working with the ESP8266 for over a year now.  Direct prices from Espressif are double for the ESP32 - though I'm sure I'll eventually go to it. 

The ESP8266 actually has plenty of resources to do what an embedded systems needs ... unless you want to gum it all up with thick layers of software like Python and HTTP+JSON processing. That is why CF  is pure C99 and a thin binary UDP protocol (\* have to get back to that, had issues with UDP and iOS app - so I think its using TCP now).

IPv6 - because for one, I have to put it in the iOS app ... apple will start requiring all iOS apps to have IPv6 support (I forget by what date). And, yes, if one wants to assess a device over the internet without a hub and cloud service proxy ... IPv6 is one solution.  I would like to see IPv6 in the NONOS SDK.  Also, its just being a good net-citizen.  IPv6 only networks will soon roll out, if not already. 

Should contact me directly - I'm easy to find on Social Media.  We should chat.  Curious about how the SmartConfig works in this system, and exactly why the 900 MHz module, but likely doesn't have to be done on this public thread.   Also interested in any sharing or collaboration - as I'd love to get rBoot and other-the-air updates working.  

chatFabric compiles on UNIX (FreeBSD confirmed, should be fine on Linux) - and could easily be used as the protocol to the cloud over UDP or TCP.

**Comment by someburner** [comment]
Yeah sounds like we might be able to collaborate on some things. I might be able to help out with rBoot and maybe some other things as I've also been working w/ the ESP8266 more-or-less full-time for a year now. I'll shoot you an email with a response a bit later.
